package br.uern.wellisonraul.metodos.mapek

import br.uern.wellisonraul.drools.Codigo;
import function br.uern.wellisonraul.metodos.mapek.Executor.resetaPadrao;
import function br.uern.wellisonraul.metodos.mapek.Executor.limpaLinhas;

dialect "java"
rule "Reseta Padrao"
    when
        c : Codigo( codigo == Codigo.RESETA)
    then
    	resetaPadrao(c.RESETA);
    	
end

rule "Limpa Arquivo"
    when
        c : Codigo( codigo == Codigo.LIMPA)
    then
    	limpaLinhas(c.LIMPA);
end